DROP TABLE STUDENT_T;
CREATE TABLE STUDENT_T(
    STUNO NUMBER NOT NULL,
    NAME VARCHAR2(100 BYTE) NOT NULL,
    KOR NUMBER NOT NULL,
    ENG NUMBER NOT NULL,
    MAT NUMBER NOT NULL,
    CONSTRAINT PK_STUDENT PRIMARY KEY(STUNO)
);

DROP SEQUENCE STUDENT_SEQ;
CREATE SEQUENCE STUDENT_SEQ NOCACHE;