DROP TABLE STUDENT_T;
CREATE TABLE STUDENT_T(
    STUDENT_NO NUMBER NOT NULL,
    NAME VARCHAR2(100 BYTE) NOT NULL,
    KOR NUMBER NOT NULL,
    ENG NUMBER NOT NULL,
    MAT NUMBER NOT NULL,
    AVERAGE NUMBER NOT NULL,
    GRADE VARCHAR2(100 BYTE) NOT NULL,
    CONSTRAINT PK_STUDENT PRIMARY KEY(STUDENT_NO)
);

DROP SEQUENCE STUDENT_SEQ;
CREATE SEQUENCE STUDENT_SEQ NOCACHE;